# Generated by Django 6.1.1 on 2026-09-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('employee', 'employee')], default='student', max_length=20),
        ),
    ]
