# Generated by Django 6.1.1 on 2026-09-20 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_app', '0005_alter_activity_options_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['send_time'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='activity',
            name='description_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='direction',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='direction',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ky',
            field=models.CharField(max_length=150, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='role_in_project_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Роль в проекте'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='role_in_project_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Роль в проекте'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='about_text_ky',
            field=models.TextField(null=True, verbose_name='О сайте'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='about_text_ru',
            field=models.TextField(null=True, verbose_name='О сайте'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='location_ky',
            field=models.CharField(max_length=150, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='location_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название задачи'),
        ),
        migrations.AddField(
            model_name='team',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='team',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ky',
            field=models.CharField(max_length=150, null=True, verbose_name='Название команды'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название команды'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_in_team_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль в команде'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_in_team_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль в команде'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ky',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position_ky',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='person',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='motion_app.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files_chat/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_chat/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
