# Generated by Django 6.1.1 on 2026-09-21 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_app', '0006_alter_chat_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True, verbose_name='Ключ')),
                ('value', models.TextField(blank=True, verbose_name='Текст')),
                ('value_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('value_ky', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ['key'],
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_general',
            field=models.BooleanField(default=False, verbose_name='Общий чат для всех сотрудников'),
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='direction',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг для фильтрации'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='project_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на демо'),
        ),
        migrations.AddField(
            model_name='project',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='projects', to='motion_app.direction', verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='task',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на GitHub'),
        ),
        migrations.AddField(
            model_name='task',
            name='result_text',
            field=models.TextField(blank=True, verbose_name='Результат работы'),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки на проверку'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='users', to='motion_app.direction', verbose_name='Навыки / технологии'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_status',
            field=models.CharField(choices=[('available', 'Готов к проекту'), ('busy', 'Занят'), ('temporarily_unavailable', 'Временно недоступен')], default='available', max_length=30, verbose_name='Рабочий статус'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('team_lead', 'Тимлид'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
